seed: 1337
dataset_number: 11300
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
generator: muongun
n_events_per_run: 10000
n_runs: 1000
e_min: 100
e_max: !!float 1e8
gamma: 2.
icemodel: SpiceLea
clsim_unshadowed_fraction: 0.9
clsim_ignore_muon_light: True
clsim_usegpus: True
muongun_e_break: 1e6
dom_oversize: 5
