chain_name: muongun_floodlight_2012_distance_split
seed: 1337
dataset_number: 11301
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
generator: muongun
n_events_per_run: 2000
n_runs: 3000
e_min: !!float 5e1
e_max: !!float 1e7
gamma: 2.
muongun_e_break: !!float 1e6
icemodel: SpiceLea
clsim_unshadowed_fraction: 0.99
clsim_ignore_muon_light: False
clsim_usegpus: True
clsim_keep_mcpe: False
clsim_dom_oversize: 5.
clsim_hybrid_mode: False
