chain_name: muongun_floodlight_2012
seed: 1337
dataset_number: 11300
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
output_pattern: '{step_name}.{dataset_number:6d}{name_addition}.{run_number}.i3.bz2'
name_addition: _HE
generator: muongun
n_events_per_run: 1000
n_runs: 1000
e_min: !!float 5e4
e_max: !!float 1e7
gamma: 2.
muongun_e_break: !!float 1e6
icemodel: SpiceLea
clsim_unshadowed_fraction: 0.9
clsim_ignore_muon_light: False
clsim_usegpus: True
clsim_keep_mcpe: False
clsim_dom_oversize: 5.
clsim_hybrid_mode: False
