chain_name: split_muongun_floodlight 
output_pattern: '{run_folder}/Level0.{step}_split_muongun_floodlight.{dataset_number:6d}.{run_number}.i3.bz2'
seed: 1337
dataset_number: 44319
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
# gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_IC86_Merged.i3.gz
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
generator: muongun
n_events_per_run: 100000 
n_runs: 100000
e_min: !!float 1e3 
e_max: !!float 1e6
gamma: 1.
zenith_min: 0.
zenith_max: 180.
muongun_e_break: 0.
icemodel: SpiceLea
distance_splits: 
DOMOversizeFactor: 5.

clsim_unshadowed_fraction: 0.99
clsim_ignore_muon_light: False
clsim_usegpus: True
clsim_keep_mcpe: False
clsim_dom_oversize: 5.
clsim_hybrid_mode: False
new_psi: 0
percentage_energy_loss: 0.4
min_dist: -100 

