chain_name: split_muongun_floodlight 
output_pattern: '{run_folder}/Level0.{step}_split_muongun_floodlight_IC86.2012_pass2.{dataset_number:6d}.{run_number}.i3.bz2'
seed: 1337
dataset_number: 44319
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2012.56063_V1.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2015.57161_V0.i3.gz
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_IC86_Merged.i3.gz
generator: muongun
n_events_per_run: 5
n_runs: 10000
e_min: !!float 1e5 
e_max: !!float 1e5
gamma: 1.
zenith_min: 0.
zenith_max: 180.
muongun_e_break: 0.
icemodel: SpiceLea
distance_splits: 

clsim_unshadowed_fraction: 0.99
clsim_ignore_muon_light: False
clsim_usegpus: True
clsim_keep_mcpe: False
clsim_dom_oversize: 5.
clsim_hybrid_mode: False
