# Nugen NuMu simulation
# 10^2 - 10^7 GeV
# Gamma = 1
# Deep-Homogenous Ice, no tilt
# DOMs on perfect hex grid

chain_name: nugen_snowstorm_split
seed: 1337

# Number of the dataset
dataset_number: 44325
# Events generated for each file
n_events_per_run: 10000
# Number of total runs/file
n_runs: 10000

e_min: !!float 1e3 # 1e2 
e_max: !!float 1e6 # 1e5
DOMOversizeFactor: 5

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz

# used icemodel
# icemodel: deep-homogenous
# For default location: leave empty
# icemodel_location: /data/user/mhuennefeld/IceModels
# Whether I3MCPE list should be stored
clsim_keep_mcpe: False

# nugen specific settings
# Neutrino flavor to simulate
# if neutrino_flavor is set, neutrino_types does
# not have any effect and I3NuGInjector is used.
# neutrino_flavor: NuMu

# Detector Simulation
# keep MCPEs in frame
det_keep_mc_hits: True
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: True
# Keep everything upto run X
det_pass2_keep_all_upto: -1
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True

NuGenSelectSplitModule: {
    new_psi: True,
    percentage_energy_loss: 0.4,
    min_dist: -100,
    beta: 1,
    perform_cut: False,
}

# select_split_module: True
# new_psi: 5 # if new_psi != 0: use brems and nuclint distributions for sampling  
# percentage_energy_loss: 0.4
# min_dist: -100 
# beta: 1
# perform_cut: False
