# Nugen NuMu simulation
# 10^2 - 10^7 GeV
# Gamma = 1
# Deep-Homogenous Ice, no tilt
# DOMs on perfect hex grid

chain_name: nugen_snowstorm_split
seed: 1337

# Number of the dataset
dataset_number: 60031
# Events generated for each file
n_events_per_run: 1000000
# Number of total runs/file
n_runs: 10000

e_min: !!float 1e4 # 1e2 
e_max: !!float 1e6 # 1e5
DOMOversizeFactor: 5

resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    0: 5gb  
    1: 3gb
    2: 5gb
    3: 3gb
    4: 3gb
    5: 5gb
  walltime:
  cpus:

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_2012: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz

# used icemodel
# icemodel: deep-homogenous
# For default location: leave empty
# icemodel_location: /data/user/mhuennefeld/IceModels
# Whether I3MCPE list should be stored
clsim_keep_mcpe: False

# nugen specific settings
# Neutrino flavor to simulate
# if neutrino_flavor is set, neutrino_types does
# not have any effect and I3NuGInjector is used.
# neutrino_flavor: NuMu

# Detector Simulation
# keep MCPEs in frame
det_keep_mc_hits: True
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: True
# Keep everything upto run X
det_pass2_keep_all_upto: -1
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True

NuGenSelectSplitModule: {
    new_psi: False,
    percentage_energy_loss: 0.4,
    min_dist: -100,
    beta: 1,
    perform_cut: False,
}


# Keep keys
additional_keep_keys: [
    'I3MapSplit',
    'I3PosOfMaxEnergyLoss',
    'OldTree',
    'OnlineL2_SplineMPE',
    'OnlineL2_SplineMPEFitParams'
]

# Bias Simulation
ApplyBaseSimulationBias: True
BaseSimulationBiasSettings: {
    'bias_function': 'UpgoingMuonStochasticity',
    'lower_probability_bound': !!float 1e-4,
    'keep_all_events': False,
    'verbose': False,
}
